import json
import os
import sys
from pprint import pprint


def get_imports():
    """
    Imports the needed modules.
    """
    try:
        return \
        """
# File generated by DLMML Parser
import sys
import os
import numpy
import pandas
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator
"""
    except Exception as e:
        print(e)
